### ISSUE TITLE
How to detect TCP disconnect 

### ISSUE THREAD

**Issue by arahasya** [Wiznet/RP2040-HAT-C#12]
I am setting pi pico as tcp client.

24 pico's are connected to a tcp server. After a few hours when the server is closed and started again some pico can be pinged but they don't connect to the server again.

I can't find the socket closed or disconnect flag / function anywhere.

Please help me. I need to detect socket disconnection immediately after the server is closed.

**Comment by GiungKim** [comment]
Hello @arahasya

'W5100S-EVB-Pico' or 'W5500-EVB-Pico', which one do you use?
 
You can get the socket status by reading the 'Sn_SR' register.

For details, refer to the 'Sn_SR' section of the datasheet below.

- W5100S-EVB-Pico → W5100S : https://docs.wiznet.io/img/products/w5100s/w5100s_ds_v127e.pdf
- W5500-EVB-Pico → W5500 : https://docs.wiznet.io/img/products/w5500/w5500_ds_v109e.pdf
