### ISSUE TITLE
HTTP Server on request function

### ISSUE THREAD

**Issue by wouterdebruijn** [Wiznet/RP2040-HAT-C#5]
I have been experimenting with the given HTTP server example code. But it seems quite basic.

I don't see an immediate way of creating a dynamic request. I would like to receive a request on a static URL, and then read that request, execute a couple function and respond to that request.

All logic is handled in the `httpServer_run` function, but this uses private functions which (i think) aren't intended to be used by me directly. Would it be better for me to create something from scratch, or should I be able to achieve this functionality by using the given library?

P.S. Sorry for creating an issue for this question. If there is a forum where these questions should be asked please let me know.

**Comment by GiungKim** [comment]
Hi @wouterdebruijn,

I'm sorry for late reply.

First, the HTTP server example provided by RP2040-HAT-C is the most basic example.

For additional implementations, you must develop your own. 

I don't know if it will be helpful, but I think it would be good to refer to the link below. 
- [WIZ550web](https://github.com/Wiznet/WIZ550web)

Sorry for not giving you good news.

P.S. If you have any questions while using WIZnet products, please leave a question on the link below. 
- [wiznet developer forum](https://forum.wiznet.io/)

**Comment by GiungKim** [comment]
Hi @wouterdebruijn,

I'm sorry for late reply.

First, the HTTP server example provided by RP2040-HAT-C is the most basic example.

For additional implementations, you must develop your own. 

I don't know if it will be helpful, but I think it would be good to refer to the link below. 
- [WIZ550web](https://github.com/Wiznet/WIZ550web)

Sorry for not giving you good news.

P.S. If you have any questions while using WIZnet products, please leave a question on the link below. 
- [Wiznet Developer Forum](https://forum.wiznet.io/)
