### ISSUE TITLE
DHCP issue

### ISSUE THREAD

**Issue by xamanimran** [Wiznet/RP2040-HAT-C#6]
I am experimenting with DHCP and DNS example. I am using W5500 and Rp2040 pico board with SPI0. I want to use DHCP to get IP. When I build and drag firmware.uf2 file in pico-board. Nothing was displayed on the terminal. I have also changed the configuration to SPI1 but nothing works. I have tested it with circuit python it works fine for me. I want to use C/C++ SDK.

`
static wiz_NetInfo g_net_info =
    {
        .mac = {0x00, 0x08, 0xDC, 0x12, 0x34, 0x56}, // MAC address
        .dhcp = NETINFO_DHCP                         // DHCP enable/disable
};
`

![Screenshot 2022-01-15 163658](https://user-images.githubusercontent.com/40911710/149620354-41f7d9b7-712d-4447-a3e3-2f2c30795f8f.png)

**Comment by GiungKim** [comment]
Hi @xamanimran,

Is there no output in the terminal program even if the device is reset after uploading F/W?

**Comment by GiungKim** [comment]
Hi @xamanimran,

Is there no output in the terminal program even if the device is reset after F/W upload?

**Comment by GiungKim** [comment]
Hi @xamanimran,

There seems to be a problem in the process of checking the version information of the chip.

W5100S is '0×51' but W5500 is '0×04'.

Can you try to fix below function(wizchip_check())? 

- W5100S 
  - function : getVER()
  - value : 0x51
- W5500
  - function : getVERSIONR()
  - value : 0x04

![image](https://user-images.githubusercontent.com/53921945/149852661-0f571689-2dc7-4b8d-ad31-90b1545e1fcd.png)

But if there's a problem while checking the chip version, the print should come out, but it's weird that it doesn't...

**Comment by GiungKim** [comment]
Hi @xamanimran,

There seems to be a problem in the process of checking the version information of the chip.

W5100S is '0×51' but W5500 is '0×04'.

Can you try to fix below function(wizchip_check())?

- W5100S
  - function : getVER()
  - value : 0x51
- W5500
  - function : getVERSIONR()
  - value : 0x04

![image](https://user-images.githubusercontent.com/53921945/149852908-0bca64ab-5a70-4273-ada0-77f8c7853bb3.png)

But if there's a problem while checking the chip version, the print should come out, but it's weird that it doesn't...

**Comment by xamanimran** [comment]
> Hi @xamanimran,
> 
> There seems to be a problem in the process of checking the version information of the chip.
> 
> W5100S is '0×51' but W5500 is '0×04'.
> 
> Can you try to fix below function(wizchip_check())?
> 
> * W5100S
>   
>   * function : getVER()
>   * value : 0x51
> * W5500
>   
>   * function : getVERSIONR()
>   * value : 0x04
> 
> ![image](https://user-images.githubusercontent.com/53921945/149852908-0bca64ab-5a70-4273-ada0-77f8c7853bb3.png)
> 
> But if there's a problem while checking the chip version, the print should come out, but it's weird that it doesn't...

Yes, this is helpful but has not resolved the problem as I have identified an issue with `wizchip_conf.h` file. 

![Screenshot 2022-01-18 120040](https://user-images.githubusercontent.com/40911710/149886553-f7cb40f0-0d43-4f15-9083-7534a0e73843.png)

when I changed the value to W5500 and hit the build button. It automatically convert to W5100S. I have deleted the build folder and tried again to build but it changed `_WIZCHIP_` value to `W5100S` from `W5500` .

**Comment by GiungKim** [comment]
Hi @xamanimran,

Did you fix the CMakeLists files or other files?

RP2040-HAT-C is implemented based on W5100S, so there are some parts that need to be fixed to use W5500.

1. Fix patch file 'rp2040_hat_c-patch.cmake'

![image](https://user-images.githubusercontent.com/53921945/149897099-488c84e0-07b7-4537-80c8-9bb61d761b0b.png)

2. Fix 'CMakeLists.txt' in 'RP2040-HAT-C\libraries\' directory

![image](https://user-images.githubusercontent.com/53921945/149897235-070c9356-7cc5-4002-ac95-9f347289f982.png)

![image](https://user-images.githubusercontent.com/53921945/149897381-a2192569-f935-4932-8e3d-5273caae0f8d.png)

3. Fix chip version check function.
→ Done

**Comment by GiungKim** [comment]
Hi @xamanimran,

Did you fix CMakeLists files or other files?

'RP2040-HAT-C' is implemented based on 'W5100S', so there are some parts that need to be fixed to use 'W5500'.

Please refer to the below.

1. Fix patch file 'rp2040_hat_c-patch.cmake'

![image](https://user-images.githubusercontent.com/53921945/149901612-b4595934-b246-4965-9bc8-65b09a77ef63.png)

2. Fix 'CMakeLists.txt' in 'RP2040-HAT-C\libraries\\' directory

![image](https://user-images.githubusercontent.com/53921945/149901659-24f28feb-c27b-4a87-92f7-74ae362a8511.png)

![image](https://user-images.githubusercontent.com/53921945/149901516-eea9442f-74e0-43d0-9a6e-a66a8e55b067.png)

3. Fix chip version check function
→ Done

**Comment by xamanimran** [comment]
> Hi @xamanimran,
> 
> Did you fix CMakeLists files or other files?
> 
> 'RP2040-HAT-C' is implemented based on 'W5100S', so there are some parts that need to be fixed to use 'W5500'.
> 
> Please refer to the below.
> 
> 1. Fix patch file 'rp2040_hat_c-patch.cmake'
> 
> ![image](https://user-images.githubusercontent.com/53921945/149901612-b4595934-b246-4965-9bc8-65b09a77ef63.png)
> 
> 2. Fix 'CMakeLists.txt' in 'RP2040-HAT-C\libraries\' directory
> 
> ![image](https://user-images.githubusercontent.com/53921945/149901659-24f28feb-c27b-4a87-92f7-74ae362a8511.png)
> 
> ![image](https://user-images.githubusercontent.com/53921945/149901516-eea9442f-74e0-43d0-9a6e-a66a8e55b067.png)
> 
> 3. Fix chip version check function
>    → Done

Thanks @GiungKim. The issue is resolved after making the above changes in respective files in `CMakefiles.txt`, `wizchip_conf.h` and `w5x00_spi.c`. Now it works for  `W5500`.
![Screenshot 2022-01-18 141538](https://user-images.githubusercontent.com/40911710/149906734-a37ee10d-9020-4091-9b62-80dc1415a1e5.png)
