### ISSUE TITLE
Http Websocket examples request

### ISSUE THREAD

**Issue by diasrobson** [Wiznet/RP2040-HAT-C#7]
Hi, there thank you for putting all this together. I do have a request through the HTTP example is extremely basic and I was wondering if you could make an example that uses Websocket and has a webpage that contains some inputs and outputs. For example, a Text Box with a submit button, a Button that toggles a pin on the RP2040, and a sort of led Indicators on the webpage that shows the state of a pin.

I know it's a lot to ask for but I really want to use these chips in one of my projects but having some trouble on where to start.

**Comment by GiungKim** [comment]
Hello @diasrobson,

I don't know if this will help, but please refer to the example in the link below.

- https://github.com/Wiznet/WIZ550web

**Comment by GiungKim** [comment]
Hello @diasrobson,

I don't know if this will help, but Please refer to the link below.

- https://github.com/Wiznet/WIZ550web

**Comment by diasrobson** [comment]
Hi @GiungKim 
I was hoping for something based around the RP2040 as the example for the stm32 is very extensive
